name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t arifhassan/github-actions-next
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{DOCKER_USERNAME}} --password-stdin
      - run: docker push arifhassan/github-actions-next:latest
